export const numbers = [
    { country: "UK", value: "44" },
    { country: "USA", value: "1" },
    { country: "Algeria", value: "213" },
    { country: "Andorra", value: "376" },
    { country: "Angola", value: "244" },
    { country: "Anguilla", value: "1264" },
    { country: "Antigua & Barbuda", value: "1268" },
    { country: "Argentina", value: "54" },
    { country: "Armenia", value: "374" },
    { country: "Aruba", value: "297" },
    { country: "Australia", value: "61" },
    { country: "Austria", value: "43" },
    { country: "Azerbaijan", value: "994" },
    { country: "Bahamas", value: "1242" },
    { country: "Bahrain", value: "973" },
    { country: "Bangladesh", value: "880" },
    { country: "Barbados", value: "1246" },
    { country: "Belarus", value: "375" },
    { country: "Belgium", value: "32" },
    { country: "Belize", value: "501" },
    { country: "Benin", value: "229" },
    { country: "Bermuda", value: "1441" },
    { country: "Bhutan", value: "975" },
    { country: "Bolivia", value: "591" },
    { country: "Bosnia Herzegovina", value: "387" },
    { country: "Botswana", value: "267" },
    { country: "Brazil", value: "55" },
    { country: "Brunei", value: "673" },
    { country: "Bulgaria", value: "359" },
    { country: "Burkina Faso", value: "226" },
    { country: "Burundi", value: "257" },
    { country: "Cambodia", value: "855" },
    { country: "Cameroon", value: "237" },
    { country: "Canada", value: "1" },
    { country: "Cape Verde Islands", value: "238" },
    { country: "Cayman Islands", value: "1345" },
    { country: "Central African Republic", value: "236" },
    { country: "Chile", value: "56" },
    { country: "China", value: "86" },
    { country: "Colombia", value: "57" },
    { country: "Comoros", value: "269" },
    { country: "Congo", value: "242" },
    { country: "Cook Islands", value: "682" },
    { country: "Costa Rica", value: "506" },
    { country: "Croatia", value: "385" },
    { country: "Cuba", value: "53" },
    { country: "Cyprus North", value: "90392" },
    { country: "Cyprus South", value: "357" },
    { country: "Czech Republic", value: "42" },
    { country: "Denmark", value: "45" },
    { country: "Djibouti", value: "253" },
    { country: "Dominica", value: "1809" },
    { country: "Dominican Republic", value: "1809" },
    { country: "Ecuador", value: "593" },
    { country: "Egypt", value: "20" },
    { country: "El Salvador", value: "503" },
    { country: "Equatorial Guinea", value: "240" },
    { country: "Eritrea", value: "291" },
    { country: "Estonia", value: "372" },
    { country: "Ethiopia", value: "251" },
    { country: "Falkland Islands", value: "500" },
    { country: "Faroe Islands", value: "298" },
    { country: "Fiji", value: "679" },
    { country: "Finland", value: "358" },
    { country: "France", value: "33" },
    { country: "French Guiana", value: "594" },
    { country: "French Polynesia", value: "689" },
    { country: "Gabon", value: "241" },
    { country: "Gambia", value: "220" },
    { country: "Georgia", value: "7880" },
    { country: "Germany", value: "49" },
    { country: "Ghana", value: "233" },
    { country: "Gibraltar", value: "350" },
    { country: "Greece", value: "30" },
    { country: "Greenland", value: "299" },
    { country: "Grenada", value: "1473" },
    { country: "Guadeloupe", value: "590" },
    { country: "Guam", value: "671" },
    { country: "Guatemala", value: "502" },
    { country: "Guinea", value: "224" },
    { country: "Guinea - Bissau", value: "245" },
    { country: "Guyana", value: "592" },
    { country: "Haiti", value: "509" },
    { country: "Honduras", value: "504" },
    { country: "Hong Kong", value: "852" },
    { country: "Hungary", value: "36" },
    { country: "Iceland", value: "354" },
    { country: "India", value: "91" },
    { country: "Indonesia", value: "62" },
    { country: "Iran", value: "98" },
    { country: "Iraq", value: "964" },
    { country: "Ireland", value: "353" },
    { country: "Israel", value: "972" },
    { country: "Italy", value: "39" },
    { country: "Jamaica", value: "1876" },
    { country: "Japan", value: "81" },
    { country: "Jordan", value: "962" },
    { country: "Kazakhstan", value: "7" },
    { country: "Kenya", value: "254" },
    { country: "Kiribati", value: "686" },
    { country: "Korea North", value: "850" },
    { country: "Korea South", value: "82" },
    { country: "Kuwait", value: "965" },
    { country: "Kyrgyzstan", value: "996" },
    { country: "Laos", value: "856" },
    { country: "Latvia", value: "371" },
    { country: "Lebanon", value: "961" },
    { country: "Lesotho", value: "266" },
    { country: "Liberia", value: "231" },
    { country: "Libya", value: "218" },
    { country: "Liechtenstein", value: "417" },
    { country: "Lithuania", value: "370" },
    { country: "Luxembourg", value: "352" },
    { country: "Macao", value: "853" },
    { country: "Macedonia", value: "389" },
    { country: "Madagascar", value: "261" },
    { country: "Malawi", value: "265" },
    { country: "Malaysia", value: "60" },
    { country: "Maldives", value: "960" },
    { country: "Mali", value: "223" },
    { country: "Malta", value: "356" },
    { country: "Marshall Islands", value: "692" },
    { country: "Martinique", value: "596" },
    { country: "Mauritania", value: "222" },
    { country: "Mayotte", value: "269" },
    { country: "Mexico", value: "52" },
    { country: "Micronesia", value: "691" },
    { country: "Moldova", value: "373" },
    { country: "Monaco", value: "377" },
    { country: "Mongolia", value: "976" },
    { country: "Montserrat", value: "1664" },
    { country: "Morocco", value: "212" },
    { country: "Mozambique", value: "258" },
    { country: "Myanmar", value: "95" },
    { country: "Namibia", value: "264" },
    { country: "Nauru", value: "674" },
    { country: "Nepal", value: "977" },
    { country: "Netherlands", value: "31" },
    { country: "New Caledonia", value: "687" },
    { country: "New Zealand", value: "64" },
    { country: "Nicaragua", value: "505" },
    { country: "Niger", value: "227" },
    { country: "Nigeria", value: "234" },
    { country: "Niue", value: "683" },
    { country: "Norfolk Islands", value: "672" },
    { country: "Northern Marianas", value: "670" },
    { country: "Norway", value: "47" },
    { country: "Oman", value: "968" },
    { country: "Palau", value: "680" },
    { country: "Panama", value: "507" },
    { country: "Papua New Guinea", value: "675" },
    { country: "Paraguay", value: "595" },
    { country: "Peru", value: "51" },
    { country: "Philippines", value: "63" },
    { country: "Poland", value: "48" },
    { country: "Portugal", value: "351" },
    { country: "Puerto Rico", value: "1787" },
    { country: "Qatar", value: "974" },
    { country: "Reunion", value: "262" },
    { country: "Romania", value: "40" },
    { country: "Russia", value: "7" },
    { country: "Rwanda", value: "250" },
    { country: "San Marino", value: "378" },
    { country: "Sao Tome & Principe", value: "239" },
    { country: "Saudi Arabia", value: "966" },
    { country: "Senegal", value: "221" },
    { country: "Serbia", value: "381" },
    { country: "Seychelles", value: "248" },
    { country: "Sierra Leone", value: "232" },
    { country: "Singapore", value: "65" },
    { country: "Slovak Republic", value: "421" },
    { country: "Slovenia", value: "386" },
    { country: "Solomon Islands", value: "677" },
    { country: "Somalia", value: "252" },
    { country: "South Africa", value: "27" },
    { country: "Spain", value: "34" },
    { country: "Sri Lanka", value: "94" },
    { country: "St. Helena", value: "290" },
    { country: "St. Kitts", value: "1869" },
    { country: "St. Lucia", value: "1758" },
    { country: "Sudan", value: "249" },
    { country: "Suriname", value: "597" },
    { country: "Swaziland", value: "268" },
    { country: "Sweden", value: "46" },
    { country: "Switzerland", value: "41" },
    { country: "Syria", value: "963" },
    { country: "Taiwan", value: "886" },
    { country: "Tajikistan", value: "7" },
    { country: "Thailand", value: "66" },
    { country: "Togo", value: "228" },
    { country: "Tonga", value: "676" },
    { country: "Trinidad & Tobago", value: "1868" },
    { country: "Tunisia", value: "216" },
    { country: "Turkey", value: "90" },
    { country: "Turkmenistan", value: "7" },
    { country: "Turkmenistan", value: "993" },
    { country: "Turks & Caicos Islands", value: "1649" },
    { country: "Tuvalu", value: "688" },
    { country: "Uganda", value: "256" },
    { country: "Ukraine", value: "380" },
    { country: "United Arab Emirates", value: "971" },
    { country: "Uruguay", value: "598" },
    { country: "Uzbekistan", value: "7" },
    { country: "Vanuatu", value: "678" },
    { country: "Vatican City", value: "379" },
    { country: "Venezuela", value: "58" },
    { country: "Vietnam", value: "84" },
    { country: "Virgin Islands - British", value: "1284" },
    { country: "Virgin Islands - US", value: "1340" },
    { country: "Wallis & Futuna", value: "681" },
    { country: "Yemen North", value: "969" },
    { country: "Yemen South", value: "967" },
    { country: "Zambia", value: "260" },
    { country: "Zimbabwe", value: "263" },
];

export const countries = [
    { name: "Afghanistan", code: "AF" },
    { name: "Åland Islands", code: "AX" },
    { name: "Albania", code: "AL" },
    { name: "Algeria", code: "DZ" },
    { name: "American Samoa", code: "AS" },
    { name: "Andorra", code: "AD" },
    { name: "Angola", code: "AO" },
    { name: "Anguilla", code: "AI" },
    { name: "Antarctica", code: "AQ" },
    { name: "Antigua and Barbuda", code: "AG" },
    { name: "Argentina", code: "AR" },
    { name: "Armenia", code: "AM" },
    { name: "Aruba", code: "AW" },
    { name: "Australia", code: "AU" },
    { name: "Austria", code: "AT" },
    { name: "Azerbaijan", code: "AZ" },
    { name: "Bahamas", code: "BS" },
    { name: "Bahrain", code: "BH" },
    { name: "Bangladesh", code: "BD" },
    { name: "Barbados", code: "BB" },
    { name: "Belarus", code: "BY" },
    { name: "Belgium", code: "BE" },
    { name: "Belize", code: "BZ" },
    { name: "Benin", code: "BJ" },
    { name: "Bermuda", code: "BM" },
    { name: "Bhutan", code: "BT" },
    { name: "Bolivia", code: "BO" },
    { name: "Bosnia and Herzegovina", code: "BA" },
    { name: "Botswana", code: "BW" },
    { name: "Bouvet Island", code: "BV" },
    { name: "Brazil", code: "BR" },
    { name: "British Indian Ocean Territory", code: "IO" },
    { name: "Brunei Darussalam", code: "BN" },
    { name: "Bulgaria", code: "BG" },
    { name: "Burkina Faso", code: "BF" },
    { name: "Burundi", code: "BI" },
    { name: "Cambodia", code: "KH" },
    { name: "Cameroon", code: "CM" },
    { name: "Canada", code: "CA" },
    { name: "Cape Verde", code: "CV" },
    { name: "Cayman Islands", code: "KY" },
    { name: "Central African Republic", code: "CF" },
    { name: "Chad", code: "TD" },
    { name: "Chile", code: "CL" },
    { name: "China", code: "CN" },
    { name: "Christmas Island", code: "CX" },
    { name: "Cocos (Keeling) Islands", code: "CC" },
    { name: "Colombia", code: "CO" },
    { name: "Comoros", code: "KM" },
    { name: "Congo", code: "CG" },
    { name: "Congo, The Democratic Republic of the", code: "CD" },
    { name: "Cook Islands", code: "CK" },
    { name: "Costa Rica", code: "CR" },
    { name: "Cote D'Ivoire", code: "CI" },
    { name: "Croatia", code: "HR" },
    { name: "Cuba", code: "CU" },
    { name: "Cyprus", code: "CY" },
    { name: "Czech Republic", code: "CZ" },
    { name: "Denmark", code: "DK" },
    { name: "Djibouti", code: "DJ" },
    { name: "Dominica", code: "DM" },
    { name: "Dominican Republic", code: "DO" },
    { name: "Ecuador", code: "EC" },
    { name: "Egypt", code: "EG" },
    { name: "El Salvador", code: "SV" },
    { name: "Equatorial Guinea", code: "GQ" },
    { name: "Eritrea", code: "ER" },
    { name: "Estonia", code: "EE" },
    { name: "Ethiopia", code: "ET" },
    { name: "Falkland Islands (Malvinas)", code: "FK" },
    { name: "Faroe Islands", code: "FO" },
    { name: "Fiji", code: "FJ" },
    { name: "Finland", code: "FI" },
    { name: "France", code: "FR" },
    { name: "French Guiana", code: "GF" },
    { name: "French Polynesia", code: "PF" },
    { name: "French Southern Territories", code: "TF" },
    { name: "Gabon", code: "GA" },
    { name: "Gambia", code: "GM" },
    { name: "Georgia", code: "GE" },
    { name: "Germany", code: "DE" },
    { name: "Ghana", code: "GH" },
    { name: "Gibraltar", code: "GI" },
    { name: "Greece", code: "GR" },
    { name: "Greenland", code: "GL" },
    { name: "Grenada", code: "GD" },
    { name: "Guadeloupe", code: "GP" },
    { name: "Guam", code: "GU" },
    { name: "Guatemala", code: "GT" },
    { name: "Guernsey", code: "GG" },
    { name: "Guinea", code: "GN" },
    { name: "Guinea-Bissau", code: "GW" },
    { name: "Guyana", code: "GY" },
    { name: "Haiti", code: "HT" },
    { name: "Heard Island and Mcdonald Islands", code: "HM" },
    { name: "Holy See (Vatican City State)", code: "VA" },
    { name: "Honduras", code: "HN" },
    { name: "Hong Kong", code: "HK" },
    { name: "Hungary", code: "HU" },
    { name: "Iceland", code: "IS" },
    { name: "India", code: "IN" },
    { name: "Indonesia", code: "ID" },
    { name: "Iran, Islamic Republic Of", code: "IR" },
    { name: "Iraq", code: "IQ" },
    { name: "Ireland", code: "IE" },
    { name: "Isle of Man", code: "IM" },
    { name: "Israel", code: "IL" },
    { name: "Italy", code: "IT" },
    { name: "Jamaica", code: "JM" },
    { name: "Japan", code: "JP" },
    { name: "Jersey", code: "JE" },
    { name: "Jordan", code: "JO" },
    { name: "Kazakhstan", code: "KZ" },
    { name: "Kenya", code: "KE" },
    { name: "Kiribati", code: "KI" },
    { name: "Korea, Democratic People'S Republic of", code: "KP" },
    { name: "Korea, Republic of", code: "KR" },
    { name: "Kuwait", code: "KW" },
    { name: "Kyrgyzstan", code: "KG" },
    { name: "Lao People'S Democratic Republic", code: "LA" },
    { name: "Latvia", code: "LV" },
    { name: "Lebanon", code: "LB" },
    { name: "Lesotho", code: "LS" },
    { name: "Liberia", code: "LR" },
    { name: "Libyan Arab Jamahiriya", code: "LY" },
    { name: "Liechtenstein", code: "LI" },
    { name: "Lithuania", code: "LT" },
    { name: "Luxembourg", code: "LU" },
    { name: "Macao", code: "MO" },
    { name: "Macedonia, The Former Yugoslav Republic of", code: "MK" },
    { name: "Madagascar", code: "MG" },
    { name: "Malawi", code: "MW" },
    { name: "Malaysia", code: "MY" },
    { name: "Maldives", code: "MV" },
    { name: "Mali", code: "ML" },
    { name: "Malta", code: "MT" },
    { name: "Marshall Islands", code: "MH" },
    { name: "Martinique", code: "MQ" },
    { name: "Mauritania", code: "MR" },
    { name: "Mauritius", code: "MU" },
    { name: "Mayotte", code: "YT" },
    { name: "Mexico", code: "MX" },
    { name: "Micronesia, Federated States of", code: "FM" },
    { name: "Moldova, Republic of", code: "MD" },
    { name: "Monaco", code: "MC" },
    { name: "Mongolia", code: "MN" },
    { name: "Montserrat", code: "MS" },
    { name: "Morocco", code: "MA" },
    { name: "Mozambique", code: "MZ" },
    { name: "Myanmar", code: "MM" },
    { name: "Namibia", code: "NA" },
    { name: "Nauru", code: "NR" },
    { name: "Nepal", code: "NP" },
    { name: "Netherlands", code: "NL" },
    { name: "Netherlands Antilles", code: "AN" },
    { name: "New Caledonia", code: "NC" },
    { name: "New Zealand", code: "NZ" },
    { name: "Nicaragua", code: "NI" },
    { name: "Niger", code: "NE" },
    { name: "Nigeria", code: "NG" },
    { name: "Niue", code: "NU" },
    { name: "Norfolk Island", code: "NF" },
    { name: "Northern Mariana Islands", code: "MP" },
    { name: "Norway", code: "NO" },
    { name: "Oman", code: "OM" },
    { name: "Pakistan", code: "PK" },
    { name: "Palau", code: "PW" },
    { name: "Palestinian Territory, Occupied", code: "PS" },
    { name: "Panama", code: "PA" },
    { name: "Papua New Guinea", code: "PG" },
    { name: "Paraguay", code: "PY" },
    { name: "Peru", code: "PE" },
    { name: "Philippines", code: "PH" },
    { name: "Pitcairn", code: "PN" },
    { name: "Poland", code: "PL" },
    { name: "Portugal", code: "PT" },
    { name: "Puerto Rico", code: "PR" },
    { name: "Qatar", code: "QA" },
    { name: "Reunion", code: "RE" },
    { name: "Romania", code: "RO" },
    { name: "Russian Federation", code: "RU" },
    { name: "RWANDA", code: "RW" },
    { name: "Saint Helena", code: "SH" },
    { name: "Saint Kitts and Nevis", code: "KN" },
    { name: "Saint Lucia", code: "LC" },
    { name: "Saint Pierre and Miquelon", code: "PM" },
    { name: "Saint Vincent and the Grenadines", code: "VC" },
    { name: "Samoa", code: "WS" },
    { name: "San Marino", code: "SM" },
    { name: "Sao Tome and Principe", code: "ST" },
    { name: "Saudi Arabia", code: "SA" },
    { name: "Senegal", code: "SN" },
    { name: "Serbia and Montenegro", code: "CS" },
    { name: "Seychelles", code: "SC" },
    { name: "Sierra Leone", code: "SL" },
    { name: "Singapore", code: "SG" },
    { name: "Slovakia", code: "SK" },
    { name: "Slovenia", code: "SI" },
    { name: "Solomon Islands", code: "SB" },
    { name: "Somalia", code: "SO" },
    { name: "South Africa", code: "ZA" },
    { name: "South Georgia and the South Sandwich Islands", code: "GS" },
    { name: "Spain", code: "ES" },
    { name: "Sri Lanka", code: "LK" },
    { name: "Sudan", code: "SD" },
    { name: "Suriname", code: "SR" },
    { name: "Svalbard and Jan Mayen", code: "SJ" },
    { name: "Swaziland", code: "SZ" },
    { name: "Sweden", code: "SE" },
    { name: "Switzerland", code: "CH" },
    { name: "Syrian Arab Republic", code: "SY" },
    { name: "Taiwan, Province of China", code: "TW" },
    { name: "Tajikistan", code: "TJ" },
    { name: "Tanzania, United Republic of", code: "TZ" },
    { name: "Thailand", code: "TH" },
    { name: "Timor-Leste", code: "TL" },
    { name: "Togo", code: "TG" },
    { name: "Tokelau", code: "TK" },
    { name: "Tonga", code: "TO" },
    { name: "Trinidad and Tobago", code: "TT" },
    { name: "Tunisia", code: "TN" },
    { name: "Turkey", code: "TR" },
    { name: "Turkmenistan", code: "TM" },
    { name: "Turks and Caicos Islands", code: "TC" },
    { name: "Tuvalu", code: "TV" },
    { name: "Uganda", code: "UG" },
    { name: "Ukraine", code: "UA" },
    { name: "United Arab Emirates", code: "AE" },
    { name: "United Kingdom", code: "GB" },
    { name: "United States", code: "US" },
    { name: "United States Minor Outlying Islands", code: "UM" },
    { name: "Uruguay", code: "UY" },
    { name: "Uzbekistan", code: "UZ" },
    { name: "Vanuatu", code: "VU" },
    { name: "Venezuela", code: "VE" },
    { name: "Viet Nam", code: "VN" },
    { name: "Virgin Islands, British", code: "VG" },
    { name: "Virgin Islands, U.S.", code: "VI" },
    { name: "Wallis and Futuna", code: "WF" },
    { name: "Western Sahara", code: "EH" },
    { name: "Yemen", code: "YE" },
    { name: "Zambia", code: "ZM" },
    { name: "Zimbabwe", code: "ZW" }
];
